// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6qrtm4DlrnLvsbNnSijLTB_2-PvyI-fk',
    appId: '1:395675714464:web:41ae60af8a60d8ae3bdac5',
    messagingSenderId: '395675714464',
    projectId: 'studybuddy-33',
    authDomain: 'studybuddy-33.firebaseapp.com',
    storageBucket: 'studybuddy-33.appspot.com',
    measurementId: 'G-ZKEFJWYC4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyaxC4PQzw3n9rl2HQAxSo7LqEAN6HEgY',
    appId: '1:395675714464:android:0ff8555b6d44e6b93bdac5',
    messagingSenderId: '395675714464',
    projectId: 'studybuddy-33',
    storageBucket: 'studybuddy-33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNjNMuj5mJVo6viB-1cxmjQ5vk_HyFDcM',
    appId: '1:395675714464:ios:bd4d8ae6c01aec603bdac5',
    messagingSenderId: '395675714464',
    projectId: 'studybuddy-33',
    storageBucket: 'studybuddy-33.appspot.com',
    iosClientId: '395675714464-89ktn9gqhf11ni8a2s0mfse7509v2o0l.apps.googleusercontent.com',
    iosBundleId: 'com.hackoders.studybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNjNMuj5mJVo6viB-1cxmjQ5vk_HyFDcM',
    appId: '1:395675714464:ios:64a578b9d3cdf1313bdac5',
    messagingSenderId: '395675714464',
    projectId: 'studybuddy-33',
    storageBucket: 'studybuddy-33.appspot.com',
    iosClientId: '395675714464-ktlt9bmvelvpqhrohcti9e6dbq6evuk6.apps.googleusercontent.com',
    iosBundleId: 'com.prerak.studybuddy',
  );
}
